name: Test and Build

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_MAPTILER_KEY: ${{ env.NEXT_PUBLIC_MAPTILER_KEY }}
      NEXT_PUBLIC_TREE_TILES_URL: ${{ env.NEXT_PUBLIC_TREE_TILES_URL }}
      NEXT_PUBLIC_MAPTILER_BASEMAP_URL: ${{ env.NEXT_PUBLIC_MAPTILER_BASEMAP_URL }}
      NEXT_PUBLIC_MATOMO_URL: ${{ env.NEXT_PUBLIC_MATOMO_URL }}
      NEXT_PUBLIC_MATOMO_SITE_ID: ${{ env.NEXT_PUBLIC_MATOMO_SITE_ID }}
      NEXT_PUBLIC_SUPABASE_PASSTHROUGH_URL: ${{ env.NEXT_PUBLIC_SUPABASE_PASSTHROUGH_URL }}
      NEXT_PUBLIC_SUPABASE_SDK_URL: ${{ env.NEXT_PUBLIC_SUPABASE_SDK_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ env.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm run type-check
      - run: npm run test:ci 
        env:
          CI: true
