name: Test and BuildFind missing env vars

on:
  push:
    branches: [ci/fix-missing-env-vars]
  pull_request:
    branches: [ci/fix-missing-env-vars]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Preview
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      NEXT_PUBLIC_SUPABASE_SDK_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_SDK_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Use Node.js (.nvmrc)
        uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}
      - run: npm ci
      - run: npm run build --if-present
        env:
          CI: true
